#!/bin/bash


# if you haven't merged your commits to master, you can find them back using the
# following command in the submodule folder:
#
#   $ git reflog


# if you want to discard all changes you have made, including any new files you
# put there or generated by the program, use:
#
#   $ git submodule foreach git checkout -- "*"
#   $ git submodule foreach git clean -f
#   $ git submodule foreach git clean -f -d


git submodule foreach echo ; echo ; git checkout master
git submodule foreach echo ; echo ; git pull

