#!/bin/bash


# if you haven't merged your commits to master, you can find them back using the
# following command in the submodule folder:
#
#   $ git reflog

git checkout master
git pull

git submodule foreach git checkout master
# if you want to discard all changes you have made, including any new files you
# put there or generated by the program, use flag -f:
if [[ $1 == '-f' ]]; then
  git submodule foreach git checkout -- "*"
  git submodule foreach git clean -f
  git submodule foreach git clean -f -d
fi
git submodule foreach git pull

