REM this requires that you have git commandline installed, and accessible in
REM PATH

REM if you haven't merged your commits to master, you can find them back using
REM the following command in the submodule folder:
REM   C:\GitRepo\SubModule> git reflog


REM if you want to discard all changes you have made, including any new files
REM you put there or generated by the program, use:
REM   C:\GitRepo\> git submodule foreach git checkout -- "*"
REM   C:\GitRepo\> git submodule foreach git clean -f
REM   C:\GitRepo\> git submodule foreach git clean -f -d

git checkout master
git pull

git submodule foreach git checkout master
git submodule foreach git pull

