git clone git@github.com:ecologylab/ecologylabFundamental.NET.git CSharp/ecologylabFundamental
git clone git@github.com:ecologylab/ecologylabGeneratedSemantics.NET.git CSharp/ecologylabGeneratedSemantics
git clone git@github.com:ecologylab/ecologylabSemantics.NET.git CSharp/ecologylabSemantics
git clone git@github.com:ecologylab/ecologylabSemanticsExamples.NET.git CSharp/ecologylabSemanticsExamples
git clone git@github.com:ecologylab/cyberneko.git Java/cyberneko
git clone git@github.com:ecologylab/ecologylabFundamental.git Java/ecologylabFundamental
git clone git@github.com:ecologylab/ecologylabGeneratedSemantics.git Java/ecologylabGeneratedSemantics
git clone git@github.com:ecologylab/ecologylabSemantics.git Java/ecologylabSemantics
git clone git@github.com:ecologylab/ecologylabSemanticsCyberneko.git Java/ecologylabSemanticsCyberneko
git clone git@github.com:ecologylab/ecologylabSemanticsExample.git Java/ecologylabSemanticsExample
git clone git@github.com:ecologylab/ecologylabSemanticsLocationAware.git Java/ecologylabSemanticsLocationAware
git clone git@github.com:ecologylab/metadataExtractor.git Java/metadataExtractor
git clone git@github.com:ecologylab/MetaMetadataRepositoryService.git Java/MetaMetadataRepositoryService
git clone git@github.com:ecologylab/simplTranslators.git Java/simplTranslators
git clone git@github.com:ecologylab/ecologylabFundamentalAndroid.git JavaAndroid/ecologylabFundamentalAndroid
git clone git@github.com:ecologylab/ecologylabSemanticsAndroid.git JavaAndroid/ecologylabSemanticsAndroid
git clone git@github.com:ecologylab/ecologylabSemanticsJavascript.git JavaScript/ecologylabSemanticsJavascript
git clone git@github.com:ecologylab/ecologylabFundamentalSun.git JavaSun/ecologylabFundamentalSun
git clone git@github.com:ecologylab/ecologylabSemanticsSun.git JavaSun/ecologylabSemanticsSun
git clone git@github.com:ecologylab/MetaMetadataRepository.git MetaMetadataRepository
